// samd21/51 serial port
//
// Copyright (C) 2018-2019  Kevin O'Connor <kevin@koconnor.net>
//
// This file may be distributed under the terms of the GNU GPLv3 license.

#include "board/armcm_boot.h" // armcm_enable_irq
#include "board/serial_irq.h" // serial_rx_data
#include "command.h" // DECL_CONSTANT_STR
#include "internal.h" // enable_pclock
#include "sched.h" // DECL_INIT

static SercomUsart *su;

void
serial_enable_tx_irq(void)
{
    su->INTENSET.reg = SERCOM_USART_INTENSET_DRE;
}

void
SERCOMx_Handler(void)
{
    uint32_t status = su->INTFLAG.reg;
    if (status & SERCOM_USART_INTFLAG_RXC)
        serial_rx_byte(su->DATA.reg);
    if (status & SERCOM_USART_INTFLAG_DRE) {
        uint8_t data;
        int ret = serial_get_tx_byte(&data);
        if (ret)
            su->INTENCLR.reg = SERCOM_USART_INTENCLR_DRE;
        else
            su->DATA.reg = data;
    }
}

#if CONFIG_ATSAMD_SERIAL_SERCOM0_DEFAULT
    #define TX_PIN_NAME "A10"
    #define TX_PIN GPIO('A', 10)
    #define RX_PIN_NAME "A11"
    #define RX_PIN GPIO('A', 11)
#elif CONFIG_ATSAMD_SERIAL_SERCOM3_DEFAULT
    #define TX_PIN_NAME "A17"
    #define TX_PIN GPIO('A', 17)
    #define RX_PIN_NAME "A16"
    #define RX_PIN GPIO('A', 16)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_DEFAULT
    #define TX_PIN_NAME "B16"
    #define TX_PIN GPIO('B', 16)
    #define RX_PIN_NAME "B17"
    #define RX_PIN GPIO('B', 17)
#endif

#if CONFIG_ATSAMD_SERIAL_SERCOM1_TX_A0
    #define TX_PIN_NAME "PA0"
    #define TX_PIN GPIO('A', 0)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_TX_A10 || CONFIG_ATSAMD_SERIAL_SERCOM2_TX_A10
    #define TX_PIN_NAME "PA10"
    #define TX_PIN GPIO('A', 10)
#elif CONFIG_ATSAMD_SERIAL_SERCOM2_TX_A12 || CONFIG_ATSAMD_SERIAL_SERCOM4_TX_A12
    #define TX_PIN_NAME "PA12"
    #define TX_PIN GPIO('A', 12)
#elif CONFIG_ATSAMD_SERIAL_SERCOM4_TX_A13
    #define TX_PIN_NAME "PA13"
    #define TX_PIN GPIO('A', 13)
#elif CONFIG_ATSAMD_SERIAL_SERCOM2_TX_A14 || CONFIG_ATSAMD_SERIAL_SERCOM4_TX_A14
    #define TX_PIN_NAME "PA14"
    #define TX_PIN GPIO('A', 14)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_TX_A16 || CONFIG_ATSAMD_SERIAL_SERCOM3_TX_A16
    #define TX_PIN_NAME "PA16"
    #define TX_PIN GPIO('A', 16)
#elif CONFIG_ATSAMD_SERIAL_SERCOM3_TX_A17
    #define TX_PIN_NAME "PA17"
    #define TX_PIN GPIO('A', 17)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_TX_A18 || CONFIG_ATSAMD_SERIAL_SERCOM3_TX_A18
    #define TX_PIN_NAME "PA18"
    #define TX_PIN GPIO('A', 18)
#elif CONFIG_ATSAMD_SERIAL_SERCOM3_TX_A20 || CONFIG_ATSAMD_SERIAL_SERCOM5_TX_A20
    #define TX_PIN_NAME "PA20"
    #define TX_PIN GPIO('A', 20)
#elif CONFIG_ATSAMD_SERIAL_SERCOM3_TX_A22 || CONFIG_ATSAMD_SERIAL_SERCOM5_TX_A22
    #define TX_PIN_NAME "PA22"
    #define TX_PIN GPIO('A', 22)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_TX_A23
    #define TX_PIN_NAME "PA23"
    #define TX_PIN GPIO('A', 23)
#elif CONFIG_ATSAMD_SERIAL_SERCOM3_TX_A24 || CONFIG_ATSAMD_SERIAL_SERCOM5_TX_A24
    #define TX_PIN_NAME "PA24"
    #define TX_PIN GPIO('A', 24)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_TX_A30
    #define TX_PIN_NAME "PA30"
    #define TX_PIN GPIO('A', 30)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_TX_A4
    #define TX_PIN_NAME "PA4"
    #define TX_PIN GPIO('A', 4)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_TX_A6
    #define TX_PIN_NAME "PA6"
    #define TX_PIN GPIO('A', 6)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_TX_A8 || CONFIG_ATSAMD_SERIAL_SERCOM2_TX_A8
    #define TX_PIN_NAME "PA8"
    #define TX_PIN GPIO('A', 8)
#elif CONFIG_ATSAMD_SERIAL_SERCOM2_TX_A9
    #define TX_PIN_NAME "PA9"
    #define TX_PIN GPIO('A', 9)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_TX_B0
    #define TX_PIN_NAME "PB0"
    #define TX_PIN GPIO('B', 0)
#elif CONFIG_ATSAMD_SERIAL_SERCOM4_TX_B10
    #define TX_PIN_NAME "PB10"
    #define TX_PIN GPIO('B', 10)
#elif CONFIG_ATSAMD_SERIAL_SERCOM4_TX_B12
    #define TX_PIN_NAME "PB12"
    #define TX_PIN GPIO('B', 12)
#elif CONFIG_ATSAMD_SERIAL_SERCOM4_TX_B14
    #define TX_PIN_NAME "PB14"
    #define TX_PIN GPIO('B', 14)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_TX_B16
    #define TX_PIN_NAME "PB16"
    #define TX_PIN GPIO('B', 16)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_TX_B2
    #define TX_PIN_NAME "PB2"
    #define TX_PIN GPIO('B', 2)
#elif CONFIG_ATSAMD_SERIAL_SERCOM3_TX_B20
    #define TX_PIN_NAME "PB20"
    #define TX_PIN GPIO('B', 20)
#elif CONFIG_ATSAMD_SERIAL_SERCOM7_TX_B21
    #define TX_PIN_NAME "PB21"
    #define TX_PIN GPIO('B', 21)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_TX_B22
    #define TX_PIN_NAME "PB22"
    #define TX_PIN GPIO('B', 22)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_TX_B24
    #define TX_PIN_NAME "PB24"
    #define TX_PIN GPIO('B', 24)
#elif CONFIG_ATSAMD_SERIAL_SERCOM2_TX_B25
    #define TX_PIN_NAME "PB25"
    #define TX_PIN GPIO('B', 25)
#elif CONFIG_ATSAMD_SERIAL_SERCOM2_TX_B26
    #define TX_PIN_NAME "PB26"
    #define TX_PIN GPIO('B', 26)
#elif CONFIG_ATSAMD_SERIAL_SERCOM4_TX_B27
    #define TX_PIN_NAME "PB27"
    #define TX_PIN GPIO('B', 27)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_TX_B30 || CONFIG_ATSAMD_SERIAL_SERCOM7_TX_B30
    #define TX_PIN_NAME "PB30"
    #define TX_PIN GPIO('B', 30)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_TX_B31
    #define TX_PIN_NAME "PB31"
    #define TX_PIN GPIO('B', 31)
#elif CONFIG_ATSAMD_SERIAL_SERCOM4_TX_B8
    #define TX_PIN_NAME "PB8"
    #define TX_PIN GPIO('B', 8)
#elif CONFIG_ATSAMD_SERIAL_SERCOM7_TX_C12
    #define TX_PIN_NAME "PC12"
    #define TX_PIN GPIO('C', 12)
#elif CONFIG_ATSAMD_SERIAL_SERCOM6_TX_C13
    #define TX_PIN_NAME "PC13"
    #define TX_PIN GPIO('C', 13)
#elif CONFIG_ATSAMD_SERIAL_SERCOM6_TX_C16
    #define TX_PIN_NAME "PC16"
    #define TX_PIN GPIO('C', 16)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_TX_C17
    #define TX_PIN_NAME "PC17"
    #define TX_PIN GPIO('C', 17)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_TX_C22
    #define TX_PIN_NAME "PC22"
    #define TX_PIN GPIO('C', 22)
#elif CONFIG_ATSAMD_SERIAL_SERCOM3_TX_C23
    #define TX_PIN_NAME "PC23"
    #define TX_PIN GPIO('C', 23)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_TX_C27
    #define TX_PIN_NAME "PC27"
    #define TX_PIN GPIO('C', 27)
#elif CONFIG_ATSAMD_SERIAL_SERCOM6_TX_C4
    #define TX_PIN_NAME "PC4"
    #define TX_PIN GPIO('C', 4)
#elif CONFIG_ATSAMD_SERIAL_SERCOM7_TX_D8
    #define TX_PIN_NAME "PD8"
    #define TX_PIN GPIO('D', 8)
#elif CONFIG_ATSAMD_SERIAL_SERCOM6_TX_D9
    #define TX_PIN_NAME "PD9"
    #define TX_PIN GPIO('D', 9)
#endif

#if CONFIG_ATSAMD_SERIAL_SERCOM1_RX_A0
    #define RX_PIN_NAME "PA0"
    #define RX_PIN GPIO('A', 0)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_RX_A1
    #define RX_PIN_NAME "PA1"
    #define RX_PIN GPIO('A', 1)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_RX_A10 || CONFIG_ATSAMD_SERIAL_SERCOM2_RX_A10
    #define RX_PIN_NAME "PA10"
    #define RX_PIN GPIO('A', 10)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_RX_A11 || CONFIG_ATSAMD_SERIAL_SERCOM2_RX_A11
    #define RX_PIN_NAME "PA11"
    #define RX_PIN GPIO('A', 11)
#elif CONFIG_ATSAMD_SERIAL_SERCOM2_RX_A12 || CONFIG_ATSAMD_SERIAL_SERCOM4_RX_A12
    #define RX_PIN_NAME "PA12"
    #define RX_PIN GPIO('A', 12)
#elif CONFIG_ATSAMD_SERIAL_SERCOM2_RX_A13 || CONFIG_ATSAMD_SERIAL_SERCOM4_RX_A13
    #define RX_PIN_NAME "PA13"
    #define RX_PIN GPIO('A', 13)
#elif CONFIG_ATSAMD_SERIAL_SERCOM2_RX_A14 || CONFIG_ATSAMD_SERIAL_SERCOM4_RX_A14
    #define RX_PIN_NAME "PA14"
    #define RX_PIN GPIO('A', 14)
#elif CONFIG_ATSAMD_SERIAL_SERCOM2_RX_A15 || CONFIG_ATSAMD_SERIAL_SERCOM4_RX_A15
    #define RX_PIN_NAME "PA15"
    #define RX_PIN GPIO('A', 15)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_RX_A16 || CONFIG_ATSAMD_SERIAL_SERCOM3_RX_A16
    #define RX_PIN_NAME "PA16"
    #define RX_PIN GPIO('A', 16)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_RX_A17 || CONFIG_ATSAMD_SERIAL_SERCOM3_RX_A17
    #define RX_PIN_NAME "PA17"
    #define RX_PIN GPIO('A', 17)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_RX_A18 || CONFIG_ATSAMD_SERIAL_SERCOM3_RX_A18
    #define RX_PIN_NAME "PA18"
    #define RX_PIN GPIO('A', 18)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_RX_A19 || CONFIG_ATSAMD_SERIAL_SERCOM3_RX_A19
    #define RX_PIN_NAME "PA19"
    #define RX_PIN GPIO('A', 19)
#elif CONFIG_ATSAMD_SERIAL_SERCOM3_RX_A20 || CONFIG_ATSAMD_SERIAL_SERCOM5_RX_A20
    #define RX_PIN_NAME "PA20"
    #define RX_PIN GPIO('A', 20)
#elif CONFIG_ATSAMD_SERIAL_SERCOM3_RX_A21 || CONFIG_ATSAMD_SERIAL_SERCOM5_RX_A21
    #define RX_PIN_NAME "PA21"
    #define RX_PIN GPIO('A', 21)
#elif CONFIG_ATSAMD_SERIAL_SERCOM3_RX_A22 || CONFIG_ATSAMD_SERIAL_SERCOM5_RX_A22
    #define RX_PIN_NAME "PA22"
    #define RX_PIN GPIO('A', 22)
#elif CONFIG_ATSAMD_SERIAL_SERCOM3_RX_A23 || CONFIG_ATSAMD_SERIAL_SERCOM5_RX_A23
    #define RX_PIN_NAME "PA23"
    #define RX_PIN GPIO('A', 23)
#elif CONFIG_ATSAMD_SERIAL_SERCOM3_RX_A24 || CONFIG_ATSAMD_SERIAL_SERCOM5_RX_A24
    #define RX_PIN_NAME "PA24"
    #define RX_PIN GPIO('A', 24)
#elif CONFIG_ATSAMD_SERIAL_SERCOM3_RX_A25 || CONFIG_ATSAMD_SERIAL_SERCOM5_RX_A25
    #define RX_PIN_NAME "PA25"
    #define RX_PIN GPIO('A', 25)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_RX_A30 || CONFIG_ATSAMD_SERIAL_SERCOM7_RX_A30
    #define RX_PIN_NAME "PA30"
    #define RX_PIN GPIO('A', 30)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_RX_A31 || CONFIG_ATSAMD_SERIAL_SERCOM7_RX_A31
    #define RX_PIN_NAME "PA31"
    #define RX_PIN GPIO('A', 31)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_RX_A4
    #define RX_PIN_NAME "PA4"
    #define RX_PIN GPIO('A', 4)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_RX_A5
    #define RX_PIN_NAME "PA5"
    #define RX_PIN GPIO('A', 5)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_RX_A6
    #define RX_PIN_NAME "PA6"
    #define RX_PIN GPIO('A', 6)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_RX_A7
    #define RX_PIN_NAME "PA7"
    #define RX_PIN GPIO('A', 7)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_RX_A8 || CONFIG_ATSAMD_SERIAL_SERCOM2_RX_A8
    #define RX_PIN_NAME "PA8"
    #define RX_PIN GPIO('A', 8)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_RX_A9 || CONFIG_ATSAMD_SERIAL_SERCOM2_RX_A9
    #define RX_PIN_NAME "PA9"
    #define RX_PIN GPIO('A', 9)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_RX_B0
    #define RX_PIN_NAME "PB0"
    #define RX_PIN GPIO('B', 0)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_RX_B1
    #define RX_PIN_NAME "PB1"
    #define RX_PIN GPIO('B', 1)
#elif CONFIG_ATSAMD_SERIAL_SERCOM4_RX_B10
    #define RX_PIN_NAME "PB10"
    #define RX_PIN GPIO('B', 10)
#elif CONFIG_ATSAMD_SERIAL_SERCOM4_RX_B11
    #define RX_PIN_NAME "PB11"
    #define RX_PIN GPIO('B', 11)
#elif CONFIG_ATSAMD_SERIAL_SERCOM4_RX_B12
    #define RX_PIN_NAME "PB12"
    #define RX_PIN GPIO('B', 12)
#elif CONFIG_ATSAMD_SERIAL_SERCOM4_RX_B13
    #define RX_PIN_NAME "PB13"
    #define RX_PIN GPIO('B', 13)
#elif CONFIG_ATSAMD_SERIAL_SERCOM4_RX_B14
    #define RX_PIN_NAME "PB14"
    #define RX_PIN GPIO('B', 14)
#elif CONFIG_ATSAMD_SERIAL_SERCOM4_RX_B15
    #define RX_PIN_NAME "PB15"
    #define RX_PIN GPIO('B', 15)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_RX_B16
    #define RX_PIN_NAME "PB16"
    #define RX_PIN GPIO('B', 16)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_RX_B17
    #define RX_PIN_NAME "PB17"
    #define RX_PIN GPIO('B', 17)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_RX_B18 || CONFIG_ATSAMD_SERIAL_SERCOM7_RX_B18
    #define RX_PIN_NAME "PB18"
    #define RX_PIN GPIO('B', 18)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_RX_B19 || CONFIG_ATSAMD_SERIAL_SERCOM7_RX_B19
    #define RX_PIN_NAME "PB19"
    #define RX_PIN GPIO('B', 19)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_RX_B2
    #define RX_PIN_NAME "PB2"
    #define RX_PIN GPIO('B', 2)
#elif CONFIG_ATSAMD_SERIAL_SERCOM7_RX_B20
    #define RX_PIN_NAME "PB20"
    #define RX_PIN GPIO('B', 20)
#elif CONFIG_ATSAMD_SERIAL_SERCOM3_RX_B21
    #define RX_PIN_NAME "PB21"
    #define RX_PIN GPIO('B', 21)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_RX_B22 || CONFIG_ATSAMD_SERIAL_SERCOM5_RX_B22
    #define RX_PIN_NAME "PB22"
    #define RX_PIN GPIO('B', 22)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_RX_B23 || CONFIG_ATSAMD_SERIAL_SERCOM5_RX_B23
    #define RX_PIN_NAME "PB23"
    #define RX_PIN GPIO('B', 23)
#elif CONFIG_ATSAMD_SERIAL_SERCOM2_RX_B24
    #define RX_PIN_NAME "PB24"
    #define RX_PIN GPIO('B', 24)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_RX_B25
    #define RX_PIN_NAME "PB25"
    #define RX_PIN GPIO('B', 25)
#elif CONFIG_ATSAMD_SERIAL_SERCOM4_RX_B26
    #define RX_PIN_NAME "PB26"
    #define RX_PIN GPIO('B', 26)
#elif CONFIG_ATSAMD_SERIAL_SERCOM2_RX_B27
    #define RX_PIN_NAME "PB27"
    #define RX_PIN GPIO('B', 27)
#elif CONFIG_ATSAMD_SERIAL_SERCOM2_RX_B28 || CONFIG_ATSAMD_SERIAL_SERCOM4_RX_B28
    #define RX_PIN_NAME "PB28"
    #define RX_PIN GPIO('B', 28)
#elif CONFIG_ATSAMD_SERIAL_SERCOM2_RX_B29 || CONFIG_ATSAMD_SERIAL_SERCOM4_RX_B29
    #define RX_PIN_NAME "PB29"
    #define RX_PIN GPIO('B', 29)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_RX_B3
    #define RX_PIN_NAME "PB3"
    #define RX_PIN GPIO('B', 3)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_RX_B30
    #define RX_PIN_NAME "PB30"
    #define RX_PIN GPIO('B', 30)
#elif CONFIG_ATSAMD_SERIAL_SERCOM5_RX_B31 || CONFIG_ATSAMD_SERIAL_SERCOM7_RX_B31
    #define RX_PIN_NAME "PB31"
    #define RX_PIN GPIO('B', 31)
#elif CONFIG_ATSAMD_SERIAL_SERCOM4_RX_B8
    #define RX_PIN_NAME "PB8"
    #define RX_PIN GPIO('B', 8)
#elif CONFIG_ATSAMD_SERIAL_SERCOM4_RX_B9
    #define RX_PIN_NAME "PB9"
    #define RX_PIN GPIO('B', 9)
#elif CONFIG_ATSAMD_SERIAL_SERCOM6_RX_C10 || CONFIG_ATSAMD_SERIAL_SERCOM7_RX_C10
    #define RX_PIN_NAME "PC10"
    #define RX_PIN GPIO('C', 10)
#elif CONFIG_ATSAMD_SERIAL_SERCOM6_RX_C11 || CONFIG_ATSAMD_SERIAL_SERCOM7_RX_C11
    #define RX_PIN_NAME "PC11"
    #define RX_PIN GPIO('C', 11)
#elif CONFIG_ATSAMD_SERIAL_SERCOM6_RX_C12
    #define RX_PIN_NAME "PC12"
    #define RX_PIN GPIO('C', 12)
#elif CONFIG_ATSAMD_SERIAL_SERCOM7_RX_C13
    #define RX_PIN_NAME "PC13"
    #define RX_PIN GPIO('C', 13)
#elif CONFIG_ATSAMD_SERIAL_SERCOM6_RX_C14 || CONFIG_ATSAMD_SERIAL_SERCOM7_RX_C14
    #define RX_PIN_NAME "PC14"
    #define RX_PIN GPIO('C', 14)
#elif CONFIG_ATSAMD_SERIAL_SERCOM6_RX_C15 || CONFIG_ATSAMD_SERIAL_SERCOM7_RX_C15
    #define RX_PIN_NAME "PC15"
    #define RX_PIN GPIO('C', 15)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_RX_C16
    #define RX_PIN_NAME "PC16"
    #define RX_PIN GPIO('C', 16)
#elif CONFIG_ATSAMD_SERIAL_SERCOM6_RX_C17
    #define RX_PIN_NAME "PC17"
    #define RX_PIN GPIO('C', 17)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_RX_C18 || CONFIG_ATSAMD_SERIAL_SERCOM6_RX_C18
    #define RX_PIN_NAME "PC18"
    #define RX_PIN GPIO('C', 18)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_RX_C19 || CONFIG_ATSAMD_SERIAL_SERCOM6_RX_C19
    #define RX_PIN_NAME "PC19"
    #define RX_PIN GPIO('C', 19)
#elif CONFIG_ATSAMD_SERIAL_SERCOM3_RX_C22
    #define RX_PIN_NAME "PC22"
    #define RX_PIN GPIO('C', 22)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_RX_C23
    #define RX_PIN_NAME "PC23"
    #define RX_PIN GPIO('C', 23)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_RX_C24 || CONFIG_ATSAMD_SERIAL_SERCOM2_RX_C24
    #define RX_PIN_NAME "PC24"
    #define RX_PIN GPIO('C', 24)
#elif CONFIG_ATSAMD_SERIAL_SERCOM0_RX_C25 || CONFIG_ATSAMD_SERIAL_SERCOM2_RX_C25
    #define RX_PIN_NAME "PC25"
    #define RX_PIN GPIO('C', 25)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_RX_C28
    #define RX_PIN_NAME "PC28"
    #define RX_PIN GPIO('C', 28)
#elif CONFIG_ATSAMD_SERIAL_SERCOM6_RX_C5
    #define RX_PIN_NAME "PC5"
    #define RX_PIN GPIO('C', 5)
#elif CONFIG_ATSAMD_SERIAL_SERCOM6_RX_C6
    #define RX_PIN_NAME "PC6"
    #define RX_PIN GPIO('C', 6)
#elif CONFIG_ATSAMD_SERIAL_SERCOM6_RX_C7
    #define RX_PIN_NAME "PC7"
    #define RX_PIN GPIO('C', 7)
#elif CONFIG_ATSAMD_SERIAL_SERCOM6_RX_D10 || CONFIG_ATSAMD_SERIAL_SERCOM7_RX_D10
    #define RX_PIN_NAME "PD10"
    #define RX_PIN GPIO('D', 10)
#elif CONFIG_ATSAMD_SERIAL_SERCOM6_RX_D11 || CONFIG_ATSAMD_SERIAL_SERCOM7_RX_D11
    #define RX_PIN_NAME "PD11"
    #define RX_PIN GPIO('D', 11)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_RX_D20 || CONFIG_ATSAMD_SERIAL_SERCOM3_RX_D20
    #define RX_PIN_NAME "PD20"
    #define RX_PIN GPIO('D', 20)
#elif CONFIG_ATSAMD_SERIAL_SERCOM1_RX_D21 || CONFIG_ATSAMD_SERIAL_SERCOM3_RX_D21
    #define RX_PIN_NAME "PD21"
    #define RX_PIN GPIO('D', 21)
#elif CONFIG_ATSAMD_SERIAL_SERCOM6_RX_D8
    #define RX_PIN_NAME "PD8"
    #define RX_PIN GPIO('D', 8)
#elif CONFIG_ATSAMD_SERIAL_SERCOM7_RX_D9
    #define RX_PIN_NAME "PD9"
    #define RX_PIN GPIO('D', 9)
#endif

DECL_CONSTANT_STR("RESERVE_PINS_serial", TX_PIN_NAME "," RX_PIN_NAME);


#if CONFIG_ATSAMD_SERIAL_SERCOM0
    #define SERCOM_ID 0
#elif  CONFIG_ATSAMD_SERIAL_SERCOM1
    #define SERCOM_ID 1
#elif  CONFIG_ATSAMD_SERIAL_SERCOM2
    #define SERCOM_ID 2
#elif  CONFIG_ATSAMD_SERIAL_SERCOM3
    #define SERCOM_ID 3
#elif  CONFIG_ATSAMD_SERIAL_SERCOM4
    #define SERCOM_ID 4
#elif  CONFIG_ATSAMD_SERIAL_SERCOM5
    #define SERCOM_ID 5
#elif  CONFIG_ATSAMD_SERIAL_SERCOM6
    #define SERCOM_ID 6
#elif  CONFIG_ATSAMD_SERIAL_SERCOM7
    #define SERCOM_ID 7
#endif 

#if CONFIG_MACH_SAMD21
    #define raw_serial_enable_irq_handlers(sercom_id) \
        armcm_enable_irq(SERCOMx_Handler, SERCOM##sercom_id##_IRQn, 0);
#elif CONFIG_MACH_SAMX5
    #define raw_serial_enable_irq_handlers(sercom_id) \
        armcm_enable_irq(SERCOMx_Handler, SERCOM##sercom_id##_0_IRQn, 0); \
        armcm_enable_irq(SERCOMx_Handler, SERCOM##sercom_id##_1_IRQn, 0); \
        armcm_enable_irq(SERCOMx_Handler, SERCOM##sercom_id##_2_IRQn, 0); \
        armcm_enable_irq(SERCOMx_Handler, SERCOM##sercom_id##_3_IRQn, 0);
#endif
// Extra definition needed to resolve parameters before name subsitution
#define serial_enable_irq_handlers(sercom_id) raw_serial_enable_irq_handlers(sercom_id)

void
serial_init(void)
{
    // Enable serial clock
    Sercom *sercom = sercom_enable_pclock(SERCOM_ID);
    // Enable pins
    uint32_t tx_rx = sercom_serial_pins(SERCOM_ID, TX_PIN, RX_PIN);
    // Configure serial
    su = &sercom->USART;
    su->CTRLA.reg = 0;
    uint32_t areg = (SERCOM_USART_CTRLA_MODE(1)
                     | SERCOM_USART_CTRLA_DORD
                     | SERCOM_USART_CTRLA_SAMPR(1)
                     | tx_rx);
    su->CTRLA.reg = areg;
    su->CTRLB.reg = SERCOM_USART_CTRLB_RXEN | SERCOM_USART_CTRLB_TXEN;
    uint32_t freq = get_pclock_frequency(SERCOM0_GCLK_ID_CORE);
    uint32_t baud8 = freq / (2 * CONFIG_SERIAL_BAUD);
    su->BAUD.reg = (SERCOM_USART_BAUD_FRAC_BAUD(baud8 / 8)
                    | SERCOM_USART_BAUD_FRAC_FP(baud8 % 8));
    // enable irqs
    su->INTENSET.reg = SERCOM_USART_INTENSET_RXC;
    su->CTRLA.reg = areg | SERCOM_USART_CTRLA_ENABLE;
    serial_enable_irq_handlers(SERCOM_ID);
}
DECL_INIT(serial_init);
